# Generated by Django 4.0.8 on 2024-01-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
