# Generated by Django 4.0.8 on 2024-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_nurse_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='contact',
        ),
        migrations.AddField(
            model_name='nurse',
            name='mobile',
            field=models.PositiveBigIntegerField(default=111),
            preserve_default=False,
        ),
    ]
