# Generated by Django 4.0.8 on 2024-01-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_nurse_contact_nurse_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nurse',
            new_name='Nurses',
        ),
    ]
