# Generated by Django 4.0.8 on 2024-01-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_document_delete_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=150)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.nurses')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
    ]
