# Generated by Django 4.0.8 on 2024-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
