# Generated by Django 4.0.8 on 2024-01-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default=12, upload_to='media/reportimages'),
            preserve_default=False,
        ),
    ]
