# Generated by Django 4.0.8 on 2024-01-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='name',
            new_name='department',
        ),
    ]
