# Generated by Django 4.0.8 on 2024-01-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_bed_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
    ]
