# Generated by Django 4.0.8 on 2024-01-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
