# Generated by Django 4.0.8 on 2024-01-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='nurse',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='app1.nurses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.department'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient'),
        ),
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient'),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.department'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.department'),
        ),
    ]
