# Generated by Django 4.0.8 on 2024-01-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_bed_nurse_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.PositiveBigIntegerField()),
                ('medicine', models.PositiveBigIntegerField()),
                ('additional', models.PositiveBigIntegerField()),
                ('tax', models.PositiveBigIntegerField()),
                ('note', models.CharField(max_length=150)),
                ('date1', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient')),
            ],
        ),
    ]
