# Generated by Django 4.0.8 on 2024-02-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_gbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('mailid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.patient')),
            ],
        ),
    ]
