# Generated by Django 4.0.8 on 2024-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_patient_mailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbill',
            name='mailid',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
